import Script from 'next/script';
import './global.css';

export const metadata = {
  title: 'Welcome to core-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <Script src='./core-components/core-navbar.umd.js'/>
      </head>
      <body>{children}</body>
    </html>
  );
}
